import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const dmsans = localFont({
    src: "../public/fonts/DMSans-VariableFont_opsz,wght.ttf",
});
export const metadata: Metadata = {
    title: "EtherLens",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={dmsans.className}>{children}</body>
        </html>
    );
}
