import type { Metadata } from "next";
import { Viewport } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ConnectkitProvider } from "@/lib/connectkit";
import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "@/components/ui/toaster";

const dmsans = localFont({
    src: "../public/fonts/DMSans-VariableFont_opsz,wght.ttf",
});
export const metadata: Metadata = {
    title: "GHO Lens",
    description: "Generated by create next app",
};

export const viewport: Viewport = {
    themeColor: [
        { media: "(prefers-color-scheme: light)", color: "white" },
        { media: "(prefers-color-scheme: dark)", color: "black" },
    ],
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={dmsans.className}>
                <ConnectkitProvider>
                    <ThemeProvider
                        attribute="class"
                        defaultTheme="dark"
                        enableSystem
                    >
                        {children}
                        <Toaster />
                    </ThemeProvider>
                </ConnectkitProvider>{" "}
            </body>
        </html>
    );
}
